config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  root to: 'home#index'

  resources :books do
    resources :likes
    resources :comments
    resource :ratings
    resource :favorites
    put 'update_status', to: 'update_book_status#update'
  end

  resources :favorites, only: [:index]
  resources :history
  resources :tops, only: %i[index]
  resources :messages, only: [:index] do
    delete :destroy, on: :collection
  end

  get 'update_avatar_users', to: 'update_avatar_users#choose_avatar', as: :choose_avatar
  put 'update_avatar_users', to: 'update_avatar_users#update_avatar_users'
end

app/views/navbar/_burger_menu.html.haml
%button.navbar-toggler.border-0{"aria-controls" => "offcanvasNavbar", "aria-label" => "Toggle navigation", "data-bs-target" => "#offcanvasNavbar", "data-bs-toggle" => "offcanvas", :type => "button"}
  %span.fs-5
    ☰
#offcanvasNavbar.offcanvas.offcanvas-end{"aria-labelledby" => "offcanvasNavbarLabel", :tabindex => "-1"}
  .offcanvas-body
    %ul.navbar-nav.justify-content-end.flex-grow-1.pe-3
      .d-block.ms-2
        .mb-3
          -if user_signed_in?
            .d-flex.align-items-center.gap-2.mb-2
              = image_tag current_user.avatar.url, class: 'rounded-circle avatar'
              %p= current_user.login
            %li
              %hr.solid
          -unless user_signed_in?
            = button_to 'Sign in/Register', new_user_session_path, method: :get, class: 'btn btn-dark rounded-5 w-100'
        .mb-3
          = link_to books_path, class: 'text-decoration-none text-dark rounded-circle' do
            .d-flex.align-items-center.gap-3
              %i.bi.bi-ui-checks-grid.fs-5
              %p.fs-6 Catalog
        .mb-3
          - if user_signed_in?
            = link_to favorites_path, class: 'text-decoration-none text-dark rounded-circle' do
              .d-flex.align-items-center.gap-3
                %i.bi.bi-bookmark.fs-5
                %p Favorites
          -else
            = link_to new_user_session_path, class: 'text-decoration-none text-dark rounded-circle' do
              .d-flex.align-items-center.gap-3
                %i.bi.bi-bookmark.fs-5
                %p Favorites
        .mb-3
          - if user_signed_in?
            = link_to messages_path, class: 'text-decoration-none text-dark' do
              .d-flex.align-items-center.gap-3
                %i.bi.bi-bell.fs-5
                %p Messages
          - else
            = link_to new_user_session_path, class: 'text-decoration-none text-dark' do
              .d-flex.align-items-center.gap-3
                %i.bi.bi-bell.fs-5
                %p Messages
        .mb-3
          = link_to tops_path, class: 'text-decoration-none text-dark' do
            .d-flex.align-items-center.gap-3
              %i.bi.bi-arrow-up-short.fs-3
              %p.fs-6 Top
        .mb-3
          - if user_signed_in?
            %li
              %hr.solid
            = button_to 'Edit profile', edit_user_registration_path, method: :get, class: 'li-dropdown text-dark mt-3 mb-2'
            - if user_signed_in? && current_user.admin
              .mb-2.mt-2
                = button_to 'Create book', new_book_path, method: :get, class: 'li-dropdown text-dark mt-2 mb-3'
            %li
              %hr.solid
            .d-flex.justify-content-between
              = button_to 'Sign out', destroy_user_session_path, method: :delete, data: { turbo: false }, class: 'li-dropdown text-dark mt-2'

app/views/navbar/_message_counter.html.haml
- if user_signed_in?
  - unread_message = current_user.messages.where(read: false).count
  - if unread_message == 0
    .btn.btn-light.rounded-circle
      %i.bi.bi-bell.fs-icon
  - if unread_message.positive?
    .d-flex.btn.btn-dark.rounded-circle.border-0
      %i.bi.bi-bell.fs-icon
      %p.fs-6.mt-auto= unread_message

app/views/navbar/_message_counter_small.html.haml
- if user_signed_in?
  - unread_message = current_user.messages.where(read: false).count
  - if unread_message == 0
    %i.bi.bi-bell.fs-icon
  - if unread_message.positive?
    .d-flex
      %i.bi.bi-bell.fs-icon
      %p.fs-6.mt-auto= unread_message

app/views/navbar/_navbar.html.haml
.navbar-big.d-none.d-sm-block
  = render 'navbar/navbar_large'
.navbar-small.d-block.d-sm-none
  = render 'navbar/navbar_small'

app/views/navbar/_navbar_large.html.haml
%nav.navbar.navbar-expand-lg.bg-body-secondary
  .container-fluid
    .d-flex.align-items-center.gap.justify-content-between
      %a.navbar-brand.align-items-start.ms-1{ href: root_path }
        %i.bi.bi-book.fs-1
      .d-flex.gap-2
        = button_to 'Catalog', books_path, method: :get, class: 'btn btn-light rounded-5 btn-navbar'
        = button_to 'Top', tops_path, method: :get, class: 'btn btn-light rounded-5 btn-navbar'
    .d-flex.align-items-center.gap-2
      = render 'navbar/search'
      - if user_signed_in? && current_user.admin
        = link_to new_book_path, class: 'text-decoration-none text-dark btn btn-light rounded-circle' do
          %i.bi.bi-plus-circle.fs-icon
      - if user_signed_in?
        = link_to favorites_path, class: 'text-decoration-none text-dark btn btn-light rounded-circle' do
          %i.bi.bi-bookmark.fs-icon
      -else
        = link_to new_user_session_path, class: 'text-decoration-none text-dark btn btn-light rounded-circle' do
          %i.bi.bi-bookmark.fs-icon
      -if user_signed_in?
        = link_to messages_path, class: 'text-decoration-none' do
          = render 'navbar/message_counter'
      - else
        = link_to new_user_session_path, class: 'text-decoration-none text-dark' do
          .btn.btn-light.rounded-circle
            %i.bi.bi-bell.fs-5
      -if user_signed_in?
        = render 'navbar/user_options'
      -unless user_signed_in?
        = button_to 'Sign in/Register', new_user_session_path, method: :get, class: 'btn btn-dark rounded-5'
%li
  %hr.solid

app/views/navbar/_navbar_small.html.haml
.container.mt-3.mb-3
  = render 'navbar/search'

%nav.navbar-small-bottom.bg-body-secondary.pt-1.pb-1
  .d-flex.gap-3.justify-content-center.align-items-center.bg-body-secondary.m-1.z-2.w-100
    = link_to books_path, class: 'text-decoration-none text-dark rounded-circle' do
      .d-flex.flex-column.align-items-center
        %i.bi.bi-ui-checks-grid.fs-6
        %p Catalog
    - if user_signed_in?
      = link_to favorites_path, class: 'text-decoration-none text-dark' do
        .d-flex.flex-column.align-items-center
          %i.bi.bi-bookmark.fs-6
          %p Favorites
    -else
      = link_to new_user_session_path, class: 'text-decoration-none text-dark rounded-circle' do
        .d-flex.flex-column.align-items-center
          %i.bi.bi-bookmark.fs-6
          %p Favorites
    %a.navbar-brand.align-items-start.ms-2.me-4{ href: root_path }
      %i.bi.bi-book.fs-1
    - if user_signed_in?
      = link_to messages_path, class: 'text-decoration-none text-dark' do
        .d-flex.flex-column.align-items-center
          = render 'navbar/message_counter_small'
          %p Messages
    - else
      = link_to new_user_session_path, class: 'text-decoration-none text-dark' do
        .d-flex.flex-column.align-items-center
          %i.bi.bi-bell.fs-6
          %p Messages
    = render 'navbar/burger_menu'

app/views/navbar/_search.html.haml
= form_with(url: root_path, method: :get, data: {turbo_frame: 'result-search', controller: 'search'}) do |f|
  = f.text_field :search, placeholder: 'Searching...', data: { action: 'input->search#search', search_target: 'input' }, class: 'form-control rounded-5 p-2 text-center search'
  = f.submit 'Search', class: 'btn btn-outline-none', hidden: true

app/views/navbar/_user_options.html.haml
.dropdown.border-secondary
  %button{"aria-expanded" => "false", "data-bs-toggle" => "dropdown", :type => "button", style: 'border: none'}
    = image_tag current_user.avatar.url, class: "rounded-circle avatar"
  %ul.dropdown-menu.dropdown-menu-end.justify-content-end.flex-grow-1.pe-3{ style: 'width: 300px' }
    .d-block.ms-4
      .mt-3.mb-2
        .d-flex.align-items-center.gap-2.mb-2.ms-0
          = image_tag current_user.avatar.url, class: 'rounded-circle avatar'
          %p= current_user.login
      %li.mt-2
        %hr.solid
      .mb-3.mt-3
        = link_to books_path, class: 'text-decoration-none text-dark rounded-circle' do
          .d-flex.align-items-center.gap-3
            %i.bi.bi-ui-checks-grid.fs-5
            %p.fs-6 Catalog
      .mb-3
        - if user_signed_in?
          = link_to favorites_path, class: 'text-decoration-none text-dark rounded-circle' do
            .d-flex.align-items-center.gap-3
              %i.bi.bi-bookmark.fs-5
              %p Favorites
        -else
          = link_to new_user_session_path, class: 'text-decoration-none text-dark rounded-circle' do
            .d-flex.align-items-center.gap-3
              %i.bi.bi-bookmark.fs-5
              %p Favorites
      .mb-3
        - if user_signed_in?
          = link_to messages_path, class: 'text-decoration-none text-dark' do
            .d-flex.align-items-center.gap-3
              %i.bi.bi-bell.fs-5
              %p Messages
        - else
          = link_to new_user_session_path, class: 'text-decoration-none text-dark' do
            .d-flex.align-items-center.gap-3
              %i.bi.bi-bell.fs-5
              %p Messages
      .mb-3
        = link_to tops_path, class: 'text-decoration-none text-dark' do
          .d-flex.align-items-center.gap-2
            %i.bi.bi-arrow-up-short.fs-3
            %p.fs-6 Top
      %li
        %hr.solid
      .mt-3
        = button_to 'Edit profile', edit_user_registration_path, method: :get, class: 'li-dropdown text-dark'
      .mt-3
        - if user_signed_in? && current_user.admin
          = button_to 'Create book', new_book_path, method: :get, class: 'li-dropdown text-dark mt-2 mb-3'
      %li
        %hr.solid
      .d-flex.justify-content-between.mt-2.mb-2
        = button_to 'Sign out', destroy_user_session_path, method: :delete, data: { turbo: false }, class: 'li-dropdown text-dark'