config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  root to: 'home#index'

  resources :books do
    resources :likes
    resources :comments
    resource :ratings
    resource :favorites
    put 'update_status', to: 'update_book_status#update'
  end

  resources :favorites, only: [:index]
  resources :history
  resources :tops, only: %i[index]
  resources :messages, only: [:index] do
    delete :destroy, on: :collection
  end

  get 'update_avatar_users', to: 'update_avatar_users#choose_avatar', as: :choose_avatar
  put 'update_avatar_users', to: 'update_avatar_users#update_avatar_users'
end

app/controllers/update_avatar_users_controller.rb
# frozen_string_literal: true

class UpdateAvatarUsersController < ApplicationController
  before_action :authenticate_user!

  def choose_avatar
    @user = current_user
    @avatars = UpdateUserAvatarService::AVATARS
  end

  def update_avatar_users
    @user = current_user

    if UpdateUserAvatarService.new(@user, params).set_user_avatar
      redirect_to edit_user_registration_path
    else
      redirect_to choose_avatar_path
    end
  end
end

app/views/update_avatar_users/_tab_content.html.haml
.d-flex.justify-content-center.flex-wrap.mt-3
  - @avatars[gender].each do |avatar|
    = button_to update_avatar_users_path, method: :put, params: { avatar: "#{gender}/#{File.basename(avatar)}" }, class: 'btn border-0' do
      = image_tag("#{gender}/#{File.basename(avatar)}", class: 'avatars')

app/views/update_avatar_users/choose_avatar.html.haml
= render 'navbar/navbar'
.container.mt-3
  .text-center.current-avatar
    -if current_user.avatar_filename.present?
      = image_tag current_user.avatar.url, class: 'rounded-circle mt-5 mb-4 current-avatar-img'
.container
  %nav
    #nav-tab.nav.nav-tabs{ :role => "tablist" }
      %button#nav-animal-tab.nav-link.active{ "aria-controls" => "nav-animal", "aria-selected" => "true", "data-bs-target" => "#nav-animal", "data-bs-toggle" => "tab", :role => "tab", :type => "button" } Animal
      %button#nav-female-tab.nav-link{ "aria-controls" => "nav-female", "aria-selected" => "false", "data-bs-target" => "#nav-female", "data-bs-toggle" => "tab", :role => "tab", :type => "button" } Women
      %button#nav-male-tab.nav-link{ "aria-controls" => "nav-male", "aria-selected" => "false", "data-bs-target" => "#nav-male", "data-bs-toggle" => "tab", :role => "tab", :type => "button" } Men
      %button#nav-custom-tab.nav-link{ "aria-controls" => "nav-custom", "aria-selected" => "false", "data-bs-target" => "#nav-custom", "data-bs-toggle" => "tab", :role => "tab", :type => "button" } Choose your avatar
    #nav-tabContent.tab-content
      #nav-animal.tab-pane.fade.show.active{ "aria-labelledby" => "nav-animal-tab", :role => "tabpanel" }
        = render partial: 'update_avatar_users/tab_content', locals: { gender: :animal }
      #nav-female.tab-pane.fade{ "aria-labelledby" => "nav-female-tab", :role => "tabpanel" }
        = render partial: 'update_avatar_users/tab_content', locals: { gender: :female }
      #nav-male.tab-pane.fade{ "aria-labelledby" => "nav-male-tab", :role => "tabpanel" }
        = render partial: 'update_avatar_users/tab_content', locals: { gender: :male }
      #nav-custom.tab-pane.fade{ 'aria-labelledby' => 'nav-custom-tab', :role => 'tabpanel' }
        = form_with(model: @user, url: update_avatar_users_path, html: { method: :put }) do |f|
          = f.file_field :avatar, autocomplete: 'avatar', class: 'form-control mt-3'
          = f.submit 'Update Avatar', class: 'btn btn-secondary mt-3'
  .d-flex.justify-content-center.mt-5
    = link_to :back, class: 'h5 ms-5 fs-2' do
      Back