config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  root to: 'home#index'

  resources :books do
    resources :likes
    resources :comments
    resource :ratings
    resource :favorites
    put 'update_status', to: 'update_book_status#update'
  end

  resources :favorites, only: [:index]
  resources :history
  resources :tops, only: %i[index]
  resources :messages, only: [:index] do
    delete :destroy, on: :collection
  end

  get 'update_avatar_users', to: 'update_avatar_users#choose_avatar', as: :choose_avatar
  put 'update_avatar_users', to: 'update_avatar_users#update_avatar_users'
end

app/models/book.rb
# frozen_string_literal: true

class Book
  include Mongoid::Document
  include Mongoid::Timestamps

  mount_uploader :image, ImageUploader

  field :title, type: String
  field :descriptions, type: String
  field :author, type: String
  field :status, type: String, default: 'Open'
  field :genre, type: String
  field :views, type: Integer, default: 0

  belongs_to :user, optional: true
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :histories, dependent: :destroy
  has_many :ratings, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :impressions, dependent: :destroy

  validates :title, presence: true, length: { maximum: 40 }
  validates :descriptions, presence: true
  validates :author, presence: true, length: { maximum: 40 }
  validates :image, presence: true

  class << self
    def search(search)
      SearchService.new(self).search(search)
    end
  end
end

app/controllers/books_controller.rb
# frozen_string_literal: true

class BooksController < ApplicationController
  before_action :authenticate_admin!, only: %i[new create update destroy]
  before_action :set_book, only: %i[show update destroy]
  before_action :filter_by_genre, only: %i[index]

  def index; end

  def show
    BookViewsService.new(current_user, @book, session).track
  end

  def new
    @new_book = Book.new
  end

  def create
    @new_book = Book.new(book_params)

    if @new_book.save
      flash[:notice] = t('book-created')
      redirect_to book_path(@new_book)
    else
      flash[:alert] = @new_book.errors.full_messages.to_sentence
      redirect_to new_book_path
    end
  end

  def update
    if @book.update(book_params)
      redirect_to book_path(@book)
    else
      redirect_to book_path(@book), alert: @book.errors.full_messages
    end
  end

  def destroy
    @book.destroy

    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.remove(helpers.dom_id(@book)) }
      format.html { redirect_to root_path, status: :see_other }
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :descriptions, :author, :image, :status, :borrowed_by, :genre)
  end

  def set_book
    @book = Book.find(params[:id])
  end

  def filter_by_genre
    @books = Book.page(params[:page]).per(20)

    @filter = if params[:genre].present?
                @books.where(genre: params[:genre])
              else
                @books
              end
  end
end

app/views/books/_books_error_message.html.haml
- if flash[:alert]
  .alert.alert-danger= flash[:alert]
- if flash[:notice]
  .alert.alert-danger= flash[:notice]

app/views/books/_comments.html.haml
- if user_signed_in?
  = turbo_frame_tag 'frame4' do
    = form_with(url: book_comments_path(@book), location: true, method: :post) do |f|
      .d-flex.mb-4
        = f.text_field :content, placeholder: 'Leave comments', class: 'form-control rounded-5'
        = button_tag class: 'border-0 bg-body-secondary' do
          %i.bi.bi-arrow-up-circle-fill.fs-3
    - @book.comments.each do |comment|
      .d-flex.gap-1.mb-3
        = image_tag comment.user.avatar.url, class: 'avatar'
        .d-block
          %p= comment.user.login
          %p.mt-2= comment.content
- else
  .d-flex.align-items-center.gap-2.mb-4
    %input.form-control.rounded-5.border-0.form-control.p-2{ type: 'text', placeholder: 'Leave comments', name: 'content' }
    = link_to new_user_session_path class: 'border-0 text-decoration-none' do
      %i.bi.bi-arrow-up-circle-fill.fs-3.border-0.bg-body-secondary.text-dark
  - @book.comments.each do |comment|
    .d-flex.gap-1.mb-3
      = image_tag comment.user.avatar.url, class: 'avatar'
      .d-block
        %p= comment.user.login
        %p.mt-2= comment.content

app/views/books/_edit_books.html.haml
- if user_signed_in? && current_user.admin
  %p.mt-2
    %a.btn.btn-dark.rounded-5.w-100{ 'aria-controls' => 'collapseExample', 'aria-expanded' => 'false', 'data-bs-toggle' => 'collapse', :href => '#collapseExample', :role => 'button' }
      Edit
  #collapseExample.collapse
    .card.card-body.mt-3
      = form_with(model: @book, method: :put, local: true) do |f|
        .field
          .mb-2
            = f.text_field :title, value: @book.title, class: 'form-control rounded-5'
          .mb-2
            = f.text_field :descriptions, value: @book.descriptions, class: 'form-control rounded-5'
          .mb-2
            = f.text_field :author, value: @book.author, class: 'form-control rounded-5'
          .mb-2
            = image_tag @book.image.url, class: 'rounded-4 w-75'
          .mb-2
            = f.file_field :image, class: 'form-control rounded-5'
        .actions
          = f.submit 'Update book', class: 'btn btn-dark form-control rounded-5'

app/views/books/_favorites.html.haml
.d-flex.align-items-center
  - if @book.favorites.exists?(user_id: current_user.id)
    = button_to book_favorites_path(book_id: @book.id), method: :delete, class: 'border-0' do
      %i.bi.bi-bookmark-dash.fs-5
  - else
    = button_to book_favorites_path(book_id: @book.id), method: :post, class: 'border-0' do
      %i.bi.bi-bookmark-plus.fs-5
  %p= "Favorites:#{@book.favorites.count}"

app/views/books/_history.html.haml
%p.d-inline-flex.gap-1
  %a.btn.btn-dark{ 'aria-controls' => 'multiCollapseExample1', 'aria-expanded' => 'false', 'data-bs-toggle' => 'collapse', :href => '#multiCollapseExample1', :role => 'button' }
    %i.bi.bi-clock-history
.row
  .col
    #multiCollapseExample1.collapse.multi-collapse.mt-3
      .card.card-body.shadow-sm.rounded-4
        %h5.text-center.mb-3.text-muted History
        - if @book.histories.present?
          - @book.histories.order_by(created_at: :desc).limit(5).each do |history|
            .border-start.border-2.border-secondary.ps-3.mb-3.position-relative
              %i.bi.bi-circle-fill.position-absolute.top-0.start-0.translate-middle.text-secondary.fs-6
              .d-flex.justify-content-between
                %p.fw-semibold.mb-1.text-dark
                  %i.bi.bi-person-fill.me-1.text-secondary
                  = "Took: #{history.user.login}"
                %small.text-muted= history.created_at.strftime('%Y-%m-%d %H:%M')
              .d-flex.justify-content-between
                %p.mb-1
                  - if history.status == 'return'
                    %i.bi.bi-arrow-return-right.me-1.text-success
                    = "Return: #{history.user.login}"
                %small.text-muted= history.updated_at.strftime('%Y-%m-%d %H:%M')
        - else
          %p.text-muted.text-center.mb-0 History is empty

app/views/books/_likes.html.haml
.d-flex.align-items-center
  - if @book.likes.exists?(user_id: current_user.id)
    = button_to book_like_path(@book), method: :delete, class: 'border-0' do
      %i.bi.bi-heart-fill
  - else
    = button_to book_likes_path(@book), method: :post, class: 'border-0' do
      %i.bi.bi-heart
  %p= "Likes:#{@book.likes.count}"

app/views/books/_rate.html.haml
- if user_signed_in?
  %button.btn.btn-light.p-0.rounded-5.btn-rating{"data-bs-target" => "#exampleModal", "data-bs-toggle" => "modal", :type => "button"}
    Rate
  #exampleModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "exampleModalLabel", :tabindex => "-1"}
    .modal-dialog.modal-dialog-centered
      .modal-content
        .modal-body
          .d-flex.justify-content-between
            %p Please, rate this book
            .text-end
              %button.btn-close{"aria-label" => "Close", "data-bs-dismiss" => "modal", :type => "button"}
          .btn-group.me-2.flexbox-item-4.d-flex.justify-content-center
            = form_with url: book_ratings_path(@book), method: :post, data: {turbo_frame: 'rating', controller: 'rating'} do |f|
              %fieldset.rating
                %input#1star5{name: "score", type: "radio", value: "5", data: { rating_target: "input", action: "change->rating#submitRating" }}/
                %label{:for => "1star5"}
                %input#1star4{name: "score", type: "radio", value: "4", data: { rating_target: "input", action: "change->rating#submitRating" }}/
                %label{:for => "1star4"}
                %input#1star3{name: "score", type: "radio", value: "3", data: { rating_target: "input", action: "change->rating#submitRating" }}/
                %label{:for => "1star3"}
                %input#1star2{name: "score", type: "radio", value: "2", data: { rating_target: "input", action: "change->rating#submitRating" }}/
                %label{:for => "1star2"}
                %input#1star1{name: "score", type: "radio", value: "1", data: { rating_target: "input", action: "change->rating#submitRating" }}/
                %label{:for => "1star1"}
              = f.submit 'Rate', class: 'btn btn-dark', hidden: true
- else
  = button_to 'Rate', new_user_session_path, class: 'btn btn-light p-0 rounded-5 btn-rating'

app/views/books/index.html.haml
= render 'navbar/navbar'
%h1.text-center Catalog

.d-flex.justify-content-center.mt-3
  = link_to 'All', books_path, class: 'btn btn-light rounded-5'
  - @books.pluck(:genre).uniq.each do |genre|
    = link_to genre, books_path(genre: genre), class: 'btn btn-light rounded-5'

.container.d-flex.align-items-center.gap-2.flex-wrap.mt-4.mb-5
  - @filter.each do |book|
    = render 'cards/cards', book: book

.container.d-flex.justify-content-center.mt-5
  =paginate @books

app/views/books/new.html.haml
= render 'navbar/navbar'
.container.mt-5
  %h1.text-center Create book
  = form_with(model: @new_book, method: 'post') do |f|
    = render 'books/books_error_message'
    .field.mt-5.mb-4
      .mb-2
        = f.text_field :title, placeholder: 'title', class: 'form-control rounded-5'
      .mb-2
        = f.text_field :descriptions, placeholder: 'descriptions', class: 'form-control rounded-5'
      .mb-2
        = f.text_field :author, placeholder: 'author', class: 'form-control rounded-5'
      .mb-2
        = f.text_field :genre, placeholder: 'genre', class: 'form-control rounded-5'
      .mb-2
        = f.file_field :image, class: 'form-control rounded-5'
    .actions
      = f.submit 'Create Book', class: 'btn btn-dark w-100'

app/views/books/show.html.haml
= render 'navbar/navbar'
.container.mt-5.mb-5
  .d-flex.flex-column.flex-md-row.gap-4.w-100
    .d-block.w-100
      .text-center
        = image_tag @book.image.url, class: 'book-one-image'
      -if user_signed_in?
        -if @book.status == 'Closed'
          = button_to 'Return book', book_update_status_path(@book), method: :put, class: 'btn btn-dark w-100 rounded-5 mt-3'
        -else
          = button_to 'Get the book', book_update_status_path(@book), method: :put, class: 'btn btn-dark w-100 rounded-5 mt-3'
      = render 'books/edit_books'
      .border.border-light.bg-light.rounded-4.p-3.mt-3
        %p= "Book status: #{@book.status}"
        - if @book.user_id.present?
          %p= "Borrowed by: #{@book.user.login}"
    .d-block
      %h1.title-book= @book.title
      .d-flex.justify-content-between.align-items-center
        %div.d-flex.align-items-center.gap-3
          - if user_signed_in?
            = turbo_frame_tag 'frame2' do
              = render 'books/likes'
          -else
            .d-flex.gap-0.align-items-center
              = button_to new_user_session_path, method: :get, class: 'border-0' do
                %i.bi.bi-heart.fs-5
              %p= "Likes:#{@book.likes.count}"
          - if @book.views.present?
            .d-flex.gap-1.align-items-center
              %i.bi.bi-eye.fs-4
              %p= @book.views
          = turbo_frame_tag 'frame3' do
            - if user_signed_in?
              = render 'books/favorites'
        .d-flex.flex-column.align-items-center.justify-content-center
          - if @book.ratings.any?
            %p.h2.text-secondary= (@book.ratings.map(&:score).sum.to_f/ @book.ratings.count).round(2)
          -else
            %p.h2.text-secondary= 0
          %p.mb-3= "#{@book.ratings.count} votes"
          = render 'books/rate'
      .border.border-light.bg-light.rounded-4.p-2{ style: 'width:50%;' }
        %p.ms-2= "Author: #{@book.author}"
        %p.ms-2.mt-1= "Genre: #{@book.genre}"
      .border.border-light.bg-light.rounded-5.p-4.mt-3
        %p= @book.descriptions
      .border.border-light.bg-light.rounded-4.p-3.mt-3
        = render 'books/history'
      .mt-3
        = render 'books/comments'