config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  root to: 'home#index'

  resources :books do
    resources :likes
    resources :comments
    resource :ratings
    resource :favorites
    put 'update_status', to: 'update_book_status#update'
  end

  resources :favorites, only: [:index]
  resources :history
  resources :tops, only: %i[index]
  resources :messages, only: [:index] do
    delete :destroy, on: :collection
  end

  get 'update_avatar_users', to: 'update_avatar_users#choose_avatar', as: :choose_avatar
  put 'update_avatar_users', to: 'update_avatar_users#update_avatar_users'
end

app/views/cards/_cards.html.haml
.card.border-0.p-0.bg-body-secondary{ style: 'max-width: 160px' }
  = link_to book_path(book), class: 'text-decoration-none' do
    .text-center
      = image_tag book.image.url, class: 'book-image rounded-4'
  .font
    %h5.card-title.text-break.mt-2.ms-2{ style: 'height: 30px' }= book.title
    -if user_signed_in?
      .d-flex.align-items-center.justify-content-between
        -if book.status == 'Closed'
          = button_to 'Return', book_update_status_path(book), method: :put, class: 'btn btn-outline-secondary ms-2'
        -else
          = button_to 'Get', book_update_status_path(book), method: :put, class: 'btn btn-outline-secondary ms-2'
        - if book.favorites.exists?(user_id: current_user.id)
          = button_to book_favorites_path(book_id: book.id), method: :delete, class: 'btn btn-light rounded-circle' do
            %i.bi.bi-bookmark-dash.fs-5
        - else
          = button_to book_favorites_path(book_id: book.id), method: :post, class: 'btn btn-light rounded-circle' do
            %i.bi.bi-bookmark-plus.fs-5
    = turbo_frame_tag "frame_#{book.id}" do
      - if user_signed_in? && current_user.admin
        = button_to book_path(book), method: :delete, data: { turbo: false, confirm: 'Are you sure you want to delete this book?' }, class: 'btn btn-dark w-100' do
          Delete